Manual turret
thedropbears/pyinfiniterecharge pull request #180
Opened 2021-04-24 02:23 UTC by OliverW10

when x is held on the co drivers gamepad they can move the turret with the left stick
it still uses the lidar to set the range as usual

2021-04-24 02:44 UTC, auscompgeek requested changes

2021-04-24 02:44 UTC, auscompgeek commented on controllers/shooter.py
> +            self.shooter.set_range(target_data.distance)
Doesn't this use the vision distance estimate unless vision is aligned?

2021-04-28 07:35 UTC, mlists commented on controllers/shooter.py
> +            self.shooter.set_range(target_data.distance)
Isn't target data a float?

2021-04-28 08:03 UTC, mlists approved these changes
Not sure how useful this is but it won't make the robot worse

2021-04-28 09:19 UTC, merged